-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [smalloc_arith]: function definitions
import Aeneas
import SmallocArith.Types
import SmallocArith.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace smalloc_arith

/-- [smalloc_arith::SMALLEST_SLOT_SIZE_BITS]
    Source: 'src/lib.rs', lines 15:0-15:43
    Visibility: public -/
@[global_simps, irreducible] def SMALLEST_SLOT_SIZE_BITS : Std.U32 := 2#u32

/-- [smalloc_arith::SMALLEST_SLOT_SIZE_BITS_MASK]
    Source: 'src/lib.rs', lines 19:0-20:44
    Visibility: public -/
@[global_simps, irreducible]
def SMALLEST_SLOT_SIZE_BITS_MASK : Result Std.Usize := do
  let i ← 1#usize <<< SMALLEST_SLOT_SIZE_BITS
  i - 1#usize

/-- [smalloc_arith::reqali_to_sc]:
    Source: 'src/lib.rs', lines 32:0-35:1
    Visibility: public -/
def reqali_to_sc (siz : Std.Usize) (ali : Std.Usize) : Result Std.U8 := do
  let i ← siz - 1#usize
  let i1 ← ali - 1#usize
  let i2 ← lift (i ||| i1)
  let i3 ← SMALLEST_SLOT_SIZE_BITS_MASK
  let i4 ← lift (i2 ||| i3)
  let i5 ← core.num.Usize.ilog2 i4
  let i6 ← i5 + 1#u32
  ok (UScalar.cast .U8 i6)

end smalloc_arith
