-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [smalloc_arith]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import SmallocArith.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open smalloc_arith

/-- [core::num::{usize}::ilog2]:
    Source: '/rustc/library/core/src/num/uint_macros.rs', lines 1766:8-1766:39
    Name pattern: [core::num::{usize}::ilog2]
    Visibility: public -/
@[rust_fun "core::num::{usize}::ilog2"]
axiom core.num.Usize.ilog2 : Std.Usize → Result Std.U32

